python -u train.py \
  --dataset_name=your_dataset_name \
  --train_root=path_to_your_training_data \
  --train_list=lists/dataset_training_list \
  --val_root=path_to_your_validation_data \
  --val_list=lists/dataset_validation_list \
  --task=stereo/flow \
  --base_lr=initial_learning_rate \
  --encoder=dlaup \
  --decoder=hda \
  --context \
  --workers=16 \
  --epochs=200 \
  --batch_size=32 \
  --evaluate \
  --batch_size_val=4 \
  --pretrain=path_to_pretrained_model \
  --visual_freq=20 \
  --save_step=50 \
  --save_path=path_to_store_model
